# Generated by Django 4.0.3 on 2022-09-02 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0003_alter_producto_descripcion_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='image1',
            field=models.ImageField(upload_to='producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='image2',
            field=models.ImageField(upload_to='producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='image3',
            field=models.ImageField(upload_to='producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='vender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=300)),
                ('imagen1', models.ImageField(upload_to='tienda')),
                ('imagen2', models.ImageField(upload_to='tienda')),
                ('imagen3', models.ImageField(upload_to='tienda')),
                ('open', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tienda',
                'verbose_name_plural': 'tiendas',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda'),
        ),
    ]
