# Generated by Django 4.0.3 on 2022-09-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
