# Generated by Django 4.0.3 on 2022-09-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0006_alter_multimedia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
