# Generated by Django 4.0.3 on 2022-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0008_alter_multimedia_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
